# Generated by Django 6.0.5 on 2026-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_user_username_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(choices=[('UN', 'Units'), ('KG', 'Kilograms'), ('G', 'Grams'), ('L', 'Liters'), ('ML', 'Milliliters')], max_length=100),
        ),
    ]
